services:
  backend:
    container_name: backend
    image: python:3.12-bullseye
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    tty: true
    command: bash -c "bash ./scripts/sh/setup_backend.sh && /bin/bash"
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
